export const PROJECT_STATUSES = [
  "ESTIMATE_STARTED", "ESTIMATE_SUBMITTED", "VENDOR_REVIEWING", "VENDOR_ACCEPTED", "VENDOR_DECLINED",
  "SITE_VISIT_SCHEDULED", "SITE_VISIT_COMPLETED", "FINAL_QUOTE_PENDING", "FINAL_QUOTE_SUBMITTED",
  "HOMEOWNER_REVIEW", "HOMEOWNER_ACCEPTED", "FINANCING_REQUESTED", "LENDER_REVIEWING",
  "ADDITIONAL_INFORMATION_NEEDED", "FINANCING_APPROVED", "FINANCING_DECLINED", "JOB_AUTHORIZED",
  "WORK_IN_PROGRESS", "CHANGE_ORDER_PENDING", "WORK_COMPLETED_BY_VENDOR", "AWAITING_HOMEOWNER_CONFIRMATION",
  "COMPLETED", "CANCELLED",
] as const;
export type ProjectStatus = (typeof PROJECT_STATUSES)[number];

export const ACTIVE_PROJECT_STATUSES: ProjectStatus[] = ["VENDOR_ACCEPTED", "SITE_VISIT_SCHEDULED", "SITE_VISIT_COMPLETED", "FINAL_QUOTE_SUBMITTED", "HOMEOWNER_ACCEPTED", "FINANCING_REQUESTED", "LENDER_REVIEWING", "FINANCING_APPROVED", "JOB_AUTHORIZED", "WORK_IN_PROGRESS", "CHANGE_ORDER_PENDING", "AWAITING_HOMEOWNER_CONFIRMATION"];

export function projectStatusLabel(status: string) { return status.replaceAll("_", " "); }
