import { requirePageAccess } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { Card, Badge } from "@/components/ui";
import { reviewFinancingStatusAction } from "@/lib/actions/admin-actions";
import { syntheticQuery } from "@/lib/task4-test-db";

type SyntheticReport = { id: string; memberName: string; email: string; companyName: string; financingAccessStatus: string; status: string; createdAt: string; disputeResponse: string | null };

export default async function AdminFinancingStatusPage() {
  await requirePageAccess("/admin/financing-status");
  const syntheticMode = process.env.SYNTHETIC_TEST_DB === "true" || process.env.DATABASE_URL?.includes("127.0.0.1:55439") === true;
  const reports = syntheticMode
    ? await syntheticQuery<SyntheticReport>('SELECT r."id", m."name" AS "memberName", m."email", p."companyName", m."financingAccessStatus", r."status", r."createdAt", d."response" AS "disputeResponse" FROM "FinancingStatusReport" r JOIN "User" m ON m."id"=r."memberId" JOIN "FinancingPartnerProfile" p ON p."id"=r."financePartnerProfileId" LEFT JOIN "FinancingStatusDispute" d ON d."reportId"=r."id" WHERE r."active"=true ORDER BY r."createdAt" DESC')
    : await prisma.financingStatusReport.findMany({ where: { active: true }, include: { member: { select: { name: true, email: true, financingAccessStatus: true } }, financePartnerProfile: { select: { companyName: true } }, disputes: { orderBy: { createdAt: "desc" } } }, orderBy: { createdAt: "desc" } });
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-brand-dark">Financing Status Reports</h1><p className="text-sm text-gray-600">Review reports without treating them as independent debt determinations or exposing reports across partners.</p></div>{reports.map((report) => { const synthetic = "memberName" in report; const member = synthetic ? { name: report.memberName, email: report.email, financingAccessStatus: report.financingAccessStatus } : report.member; const partner = synthetic ? { companyName: report.companyName } : report.financePartnerProfile; const dispute = synthetic ? report.disputeResponse : report.disputes[0]?.response; return <Card key={report.id}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-gray-900">{member.name} · {partner.companyName}</p><p className="text-sm text-gray-600">{member.email} · {report.status} · {new Date(report.createdAt).toLocaleString()}</p><p className="mt-2 text-xs text-gray-500">Member financing access: {member.financingAccessStatus}</p></div><Badge tone={report.status === "CURRENT" ? "green" : "yellow"}>{report.status}</Badge></div>{dispute && <p className="mt-3 rounded-md bg-gray-50 p-3 text-sm text-gray-700">Member response: {dispute}</p>}<form action={reviewFinancingStatusAction} className="mt-4 flex flex-wrap gap-2"><input type="hidden" name="reportId" value={report.id} /><input name="reason" placeholder="Review reason" className="rounded-md border border-gray-300 px-2 py-1 text-sm" /><button name="decision" value="KEEP_RESTRICTION" className="rounded-md border border-yellow-300 px-3 py-1.5 text-xs font-medium text-yellow-800">Keep Restriction</button><button name="decision" value="RESTORE_ACCESS" className="rounded-md bg-brand px-3 py-1.5 text-xs font-medium text-white">Restore Access</button><button name="decision" value="MARK_ERROR" className="rounded-md border border-red-300 px-3 py-1.5 text-xs font-medium text-red-700">Mark Report Error</button><button name="decision" value="RESOLVE" className="rounded-md border border-gray-300 px-3 py-1.5 text-xs font-medium">Resolve</button></form></Card>; })}{!reports.length && <Card><p className="text-sm text-gray-600">No active financing status reports.</p></Card>}</div>;
}
