import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';
const require=createRequire(new URL('../../node_modules/.cache/membership-tools/package.json',import.meta.url));const {chromium}=require('playwright');
const base='http://127.0.0.1:3000';const query=async(sql,params=[])=>{const r=await fetch('http://127.0.0.1:55440',{method:'POST',body:JSON.stringify({sql,params})});if(!r.ok)throw Error(await r.text());return r.json()};
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const results=[];const pass=s=>{results.push(s);console.log('PASS',s)};
async function login(id){const c=await browser.newContext();const p=await c.newPage();await p.goto(base+'/login');await p.getByLabel('Email',{exact:true}).fill(id+'@example.test');await p.getByLabel('Password',{exact:true}).fill('Review-only-Password42');await p.getByRole('button',{name:'Sign In',exact:true}).click();await p.waitForURL('**/welcome');await p.getByRole('button',{name:'Continue now'}).click();await p.waitForURL(u=>u.pathname!='/welcome');return {c,p};}
const replay=async(c,r)=>c.request.post(base+'/',{headers:{'next-action':r.headers()['next-action'],'content-type':r.headers()['content-type'],origin:base},data:r.postDataBuffer()});
try{
 await query('DELETE FROM "AuthThrottle"');const admin=await login('test-admin');
 for(const [role,path] of [['VENDOR','/admin/vendors/vp'],['FINANCING_PARTNER','/admin/financing-partners/fp']]) {
  await admin.p.goto(base+path);const pending=admin.p.waitForRequest(r=>r.method()==='POST'&&!!r.headers()['next-action']);await admin.p.getByRole('button',{name:'Approve Account',exact:true}).click();const req=await pending;await admin.p.getByText(/Account: APPROVED/).waitFor();
  await query('UPDATE "NetworkAgreement" SET active=false WHERE role=$1',[role]);const before=(await query('SELECT count(*)::int n FROM "ApprovalAudit"'))[0].n;
  await replay(admin.c,req);assert.equal((await query('SELECT count(*)::int n FROM "ApprovalAudit"'))[0].n,before);await query('UPDATE "NetworkAgreement" SET active=true WHERE role=$1',[role]);pass(role+': forged admin approval request cannot bypass missing agreement');
 }
 const member=await login('test-member');await member.p.goto(base+'/member/service-request');await member.p.getByLabel('Service Type').selectOption('Plumbing');const label='Blocked replay '+Date.now();await member.p.locator('textarea[name="description"]').fill(label);const pending=member.p.waitForRequest(r=>r.method()==='POST'&&!!r.headers()['next-action']);await member.p.getByRole('button',{name:/Submit/}).click();const req=await pending;await member.p.getByText(label,{exact:true}).waitFor();
 const before=(await query('SELECT count(*)::int n FROM "ServiceRequest"'))[0].n;
 await query('UPDATE "User" SET "approvalStatus"=\'PENDING\' WHERE id=\'test-member\'');await replay(member.c,req);assert.equal((await query('SELECT count(*)::int n FROM "ServiceRequest"'))[0].n,before);assert.equal((await member.c.request.get(base+'/api/documents/fake')).status(),403);
 await query('UPDATE "User" SET "approvalStatus"=\'APPROVED\' WHERE id=\'test-member\'');await query('UPDATE "NetworkAgreement" SET active=false WHERE role=\'HOMEOWNER\'');await replay(member.c,req);assert.equal((await query('SELECT count(*)::int n FROM "ServiceRequest"'))[0].n,before);await query('UPDATE "NetworkAgreement" SET active=true WHERE role=\'HOMEOWNER\'');pass('Authenticated server-action replay fails after approval revocation or agreement removal');
 await query('DELETE FROM "AgreementAcceptance" WHERE "userId"=\'test-member\'');await member.p.goto(base+'/member');assert.equal(new URL(member.p.url()).pathname,'/agreement');assert.equal((await member.c.request.post(base+'/api/chat',{data:{}})).status(),403);await query(`INSERT INTO "AgreementAcceptance" (id,"userId",role,version) VALUES ('restored-member','test-member','HOMEOWNER','test-v1')`);pass('User approval/version fields without acceptance audit cannot unlock services');
 await member.c.close();await admin.c.close();writeFileSync('docs/security-review/bypass-results.json',JSON.stringify({testedAt:new Date().toISOString(),results},null,2));
}finally{await browser.close()}
