import { requirePageAccess } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getStripe } from "@/lib/stripe";
import { Card } from "@/components/ui";
import RefundForm from "./RefundForm";

export default async function AdminBixyPaymentsPage() {
  await requirePageAccess("/admin/bixy-payments");
  const entitlements = await prisma.characterEntitlement.findMany({ where: { stripePaymentIntentId: { not: null } }, include: { user: true }, orderBy: { purchasedAt: "desc" } });
  const stripe = getStripe();
  const payments = await Promise.all(entitlements.map(async entitlement => { const paymentIntentId = entitlement.stripePaymentIntentId!; try { const intent = await stripe.paymentIntents.retrieve(paymentIntentId); const refunds = await stripe.refunds.list({ payment_intent: paymentIntentId, limit: 100 }); const refunded = refunds.data.filter(refund => refund.status !== "failed" && refund.status !== "canceled").reduce((sum, refund) => sum + refund.amount, 0); return { entitlement, intent, refunds, refunded, remaining: Math.max(0, (intent.amount_received || intent.amount) - refunded) }; } catch { return null; } }));
  const validPayments = payments.filter((payment): payment is NonNullable<typeof payment> => payment !== null);
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-brand-dark">Bixy Payments</h1><p className="text-sm text-gray-600">Admin-only Stripe payment and refund management. Stripe remains authoritative for payment/refund status.</p></div>{validPayments.map(({ entitlement, intent, refunds, refunded, remaining }) => <Card key={entitlement.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-semibold text-gray-900">{entitlement.user.name} · {entitlement.user.email}</p><p className="mt-1 text-xs text-gray-600">PaymentIntent: {intent.id}</p><p className="text-xs text-gray-600">Plan: {entitlement.plan ?? "Unknown"} · Purchased: {entitlement.purchasedAt?.toLocaleString() ?? "Unknown"}</p><p className="mt-2 text-sm">Original: ${(intent.amount / 100).toFixed(2)} · Status: {intent.status} · Refunded: ${(refunded / 100).toFixed(2)} · Remaining: ${(remaining / 100).toFixed(2)}</p><p className="text-xs text-gray-600">Bixy access: {entitlement.status} · Paid seconds remaining: {entitlement.paidSecondsRemaining}</p>{refunds.data.length > 0 && <ul className="mt-2 space-y-1 text-xs text-gray-600">{refunds.data.map((refund: { id: string; status: string | null; amount: number; created: number }) => <li key={refund.id}>{refund.id} · {refund.status} · ${(refund.amount / 100).toFixed(2)} · {new Date(refund.created * 1000).toLocaleString()}</li>)}</ul>}</div><div className="min-w-64"><RefundForm userId={entitlement.userId} paymentIntentId={intent.id} originalCents={intent.amount_received || intent.amount} remainingCents={remaining} /><a href={`https://dashboard.stripe.com/payments/${intent.id}`} target="_blank" rel="noreferrer" className="mt-2 block text-xs font-semibold text-brand underline">Open Stripe Dashboard</a></div></div></Card>)}</div>;
}
